### ISSUE TITLE
.NET Core compatibility

### ISSUE THREAD

**Issue by creativesuspects** [wildbit/css-inliner#6]
Any idea if and when this package will be ported to / targeted for net5.0 (and up)? I've included the package in a net5.0 project and everything seems to work, but I am getting these warnings:

```
NU1701: Package 'StyleMerge 1.0.28' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
```

Or do you perhaps know of a similar package that is already fully net5.0 compatible?

**Comment by Archanian** [comment]
@creativesuspects the latest version of this package targets netstandard2.0, and so should be good to use in net5.0.
